f

diff --git a/.github/actions/common/lefthook/action.yml b/.github/actions/common/lefthook/action.yml
--- a/.github/actions/common/lefthook/action.yml
+++ b/.github/actions/common/lefthook/action.yml
@@ -8,28 +8,8 @@ inputs:
 runs:
   using: composite
   steps:
-    - id: get-branch
-      if: github.event_name == 'issue_comment' && github.event.issue.pull_request != null
-      run: echo "branch=$(gh pr view "$PR_NO" --repo "$REPO" --json headRefName --jq '.headRefName')" >> "$GITHUB_OUTPUT"
-      env:
-        REPO: ${{ github.repository }}
-        PR_NO: ${{ github.event.issue.number }}
-        GH_TOKEN: ${{ inputs.token }}
-      shell: bash
-
     - name: Checkout PR branch
       uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
-      with:
-        ref: ${{ (github.event_name == 'issue_comment' && github.event.issue.pull_request != null) && steps.get-branch.outputs.branch || github.head_ref }}
-
-    - name: comment if triggered by comment
-      if: github.event_name == 'issue_comment' && github.event.issue.pull_request != null
-      run: |
-        url=$(gh pr comment "${{ github.event.issue.number }}" --body "Lefthook is running 🚀")
-        echo "comment_url=${url}" >> "$GITHUB_OUTPUT"
-      env:
-        GH_TOKEN: ${{ inputs.token }}
-      shell: bash
 
     - name: Set up pixi
       uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
@@ -57,7 +37,7 @@ runs:
       shell: bash
 
     - name: Auto commit fixes
-      if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request != null && contains(github.event.comment.body, 'lefthook') && !cancelled() }}
+      if: ${{ github.event_name == 'workflow_call' && !cancelled() }}
       run: |
         rm ./lefthook.yaml
         rm -rf ./lefthook
@@ -87,7 +67,7 @@ runs:
         fi
 
         # Always attempt to comment
-        gh pr comment "${GITHUB_EVENT_ISSUE_NUMBER}" --edit-last --body "${COMMENT_BODY}" || echo "Failed to comment on PR"
+        gh pr comment "${{ github.event.pull_request.number }}" --edit-last --body "${COMMENT_BODY}" || echo "Failed to comment on PR"
       env:
         GH_TOKEN: ${{ inputs.token }}
       shell: bash
